services:

  model-api:
    build: ./api
    volumes:
      - ./data:/opt/ml/data:rw
      - ./logs:/opt/ml/logs:rw
    ports:
      - 8080:8080

  shiny-app:
    depends_on:
      - model-api
    build: ./app
    volumes:
      - ./logs:/app/logs:rw
    ports:
      - 3838:3838
