# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_folder(path = "/opt/ml/data/model")
v <- vetiver_pin_read(b, "penguin_lm")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
